### ISSUE TITLE
License & copyright

### ISSUE THREAD

**Issue by ara4n** [illicitonion/slackbridge#1]
Herro - is there any chance of articulating a license & copyright on this, so we can try to further it in matrix proper?

**Comment by illicitonion** [comment]
The licence for this (which I would have guessed I would have published
already, boo me if not) is Apache 2, copyright matrix.org. I will add a
licence file when I'm back near a computer in July.

On Monday, 23 May 2016, Matthew Hodgson notifications@github.com wrote:

> Herro - is there any chance of articulating a license & copyright on this,
> so we can try to further it in matrix proper?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/illicitonion/slackbridge/issues/1

## 

Sent from a device smaller than my head.

**Comment by ara4n** [comment]
thanks!

**Comment by illicitonion** [comment]
Added LICENSE :)
